name: Jira summary Action
description: Posts a comment with the summary of a linked Jira story.
inputs:
  JIRA_BASE_URL:
    description: The Jira base url
    required: true

  JIRA_USER_EMAIL:
    description: The Jira user email
    required: true

  JIRA_API_TOKEN:
    description: The Jira API token for the specified user email
    required: true

  JIRA_KEY:
    description: The project key prefix to look for - or the full story key.
    required: true

  GITHUB_TOKEN:
    description: The GitHub Token to use, e.g. GITHUB_TOKEN
    required: true

outputs:
  title:
    description: The title of the Jira story

runs:
  using: node20
  main: dist/index.js
