name: Jira summary Action
description: Posts a comment with the summary of a linked Jira story.
inputs:
  jira-base-url:
    description: The Jira base url
    required: true

  jira-user-email:
    description: The Jira user email
    required: true

  jira-api-token:
    description: The Jira API token for the specified user email
    required: true

  jira-key:
    description: The project key prefix to look for - or the full story key.
    required: true

  github-token:
    description: The GitHub Token to use, e.g. GITHUB_TOKEN
    required: true

outputs:
  title:
    description: The title of the Jira story

runs:
  using: node20
  main: dist/index.js
