on:
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ opened, closed, synchronize, edited ]

jobs:
  run-jira-summary-action:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    name: Get Jira story summary
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
      
      - id: story
        name: Get summary from Jira
        uses: ./
        with:
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          jira-key: OM20-1075
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Print the summary
        run: echo "The title is ${{ steps.story.outputs.title }}"
