on:
  pull_request:
    types: [ opened, closed, synchronize, edited ]

jobs:
  run-jira-summary-action:
    runs-on: ubuntu-latest
    name: Get Jira story summary
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
      
      - id: story
        name: Get summary from Jira
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_KEY: OM20-1075
      
      - name: Print the summary
        run: echo "The title is ${{ steps.story.outputs.title }}"
